<Gerenciador>:
    PanelPrincipal:
        name: 'panelprincipal'

<PanelPrincipal>:
    BoxLayout:
        orientation: 'vertical'
        ActionBar:
            ActionView:
                ActionPrevious:
                    title: 'Gen ANKI - flashcards'
                ActionButton:
                    text: 'Exit'
                    on_release: root.confirmacao()
        BoxLayout:
            orientation: 'vertical'
            padding: root.width*0.25, root.height*0.1
            spacing: '30dp'
            Image:
                source: 'media/confia.png'
                size_hint_y: 4
                allow_stretch: True
            FloatLayout:
                Spinner:
                    id: lang
                    size_hint: None, None
                    size: 100, 44
                    pos_hint: {'center': (.5, .5)}
                    text: 'en'
                    values: 'en', 'es', 'fr', 'zh-CN'
            CustumButton:
                text: 'Gen Basic Cards'
                on_release: root.gen_basic_cards()
            CustumButton:
                text: 'Gen Intermediary Cards'
                on_release: root.gen_intermediary_cards()
            CustumButton:
                text: 'Gen Advanced Cards'
                on_release: root.gen_advanced_cards()
