#:include Menu menu.menu.Menu
#:include BasicCardsScreen basic_cards_screen.basic_cards_screen.BasicCardsScreen
#:include IntermediaryCardsScreen intermediary_cards_screen.intermediary_cards_screen.IntermediaryCardsScreen


<MainScreenManager>:
    Menu:
        name: 'menu'
    BasicCardsScreen:
        name: 'basic_cards_screen'
    IntermediaryCardsScreen:
        name: 'intermediary_cards_screen'
